"""Xray REST client. Endpoints come from xray_endpoints.py, which is generated
from agent-qa/framework/xray/api-contract.md. Never hardcode a URL here.

Authentication differs by flavour (api-contract.md, "Flavour differences at a
glance" and the per-flavour "1. Authentication -- auth" sections):

- Cloud is a token exchange: POST client_id/client_secret to the "auth" endpoint
  and receive a bare, quoted JSON string containing a 24h JWT. authenticate()
  caches and returns that token; callers send it as "Bearer {token}".
- Server/DC has no token-exchange endpoint at all. Its "auth" URL is Jira's own
  GET {base_url}/rest/api/2/myself -- a credential-validation probe that returns
  a user profile, never a token. The PAT itself is the credential; authenticate()
  GETs /myself with the PAT already in the Authorization header, treats a 200 as
  proof the PAT is valid, and returns that same "Bearer {pat}" header value for
  reuse on every later request. AUTH_STYLE["server"] records this as
  style "per_request_header", sends_body False -- the authoritative signal that
  no exchange call should be made and no token should be parsed out of the body.
"""

import base64
import json
import os
import subprocess
import time
import urllib.parse
import urllib.request
import urllib.error

from xray_endpoints import (
    AUTH_STYLE,
    CONTRACT_DOC,
    DEFAULT_CLOUD_HOST,
    ENDPOINTS,
    FEATURE_IMPORT_PARTS,
    IMPORT_JOB_STATUSES,
    IMPORT_TESTS_STATUS,
    LIMITS,
    SERVER_TEST_STEP_URL,
)


class XrayError(Exception):
    """Every failure this client raises. Never contains a credential."""


class Transport:
    def request(self, method, url, headers=None, body=None):
        raise NotImplementedError


class UrllibTransport(Transport):
    def request(self, method, url, headers=None, body=None):
        req = urllib.request.Request(url, data=body, method=method)
        for k, v in (headers or {}).items():
            req.add_header(k, v)
        try:
            with urllib.request.urlopen(req) as resp:
                return resp.status, dict(resp.headers), resp.read()
        except urllib.error.HTTPError as e:
            return e.code, dict(e.headers or {}), e.read()
        except urllib.error.URLError as e:
            raise XrayError("could not reach Xray: %s" % e.reason)


def empty_results():
    """The unified result contract every import path returns, whatever the
    flavour. Callers never branch on platform to read a result."""
    return {"created": [], "updated": [], "failed": []}


def merge_results(target, addition):
    """Accumulate one import's outcome into a running total, in place."""
    for key in ("created", "updated", "failed"):
        target[key].extend(addition.get(key, []))
    return target


_MULTIPART_BOUNDARY = "----agentqa-xray-upload-boundary"


def _sanitise_filename(name):
    # A quote or CR/LF in a filename would break out of the Content-Disposition
    # header. Nothing generated by Agent-QA contains one, but the value comes
    # from the filesystem, so it is not this function's place to assume that.
    return "".join(c for c in name if c not in '"\r\n\\') or "import.feature"


def _encode_multipart_file(part_name, filename, content):
    """Build a multipart/form-data body carrying exactly one file part.

    The standard library ships no multipart encoder, and this project takes no
    third-party dependency, so the bytes are assembled by hand. Returns
    (body_bytes, content_type_header_value).
    """
    boundary = _MULTIPART_BOUNDARY.encode()
    disposition = ('Content-Disposition: form-data; name="%s"; filename="%s"'
                   % (part_name, _sanitise_filename(filename))).encode()
    body = b"\r\n".join([
        b"--" + boundary,
        disposition,
        b"Content-Type: application/octet-stream",
        b"",
        content,
        b"--" + boundary + b"--",
        b"",
    ])
    return body, "multipart/form-data; boundary=%s" % _MULTIPART_BOUNDARY


def read_credentials(path):
    """Read the secrets file, refusing if git tracks it."""
    tracked = subprocess.run(
        ["git", "ls-files", "--error-unmatch", path],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
    ).returncode == 0
    if tracked:
        raise XrayError(
            "%s is tracked by git. Remove it from version control before uploading; "
            "a credential must never be committed." % path
        )
    creds = {}
    with open(path) as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            creds[k.strip()] = v.strip()
    return creds


class XrayClient:

    # Cloud's bulk test import is asynchronous, so the client polls. A job that
    # never resolves must end the run as a FAILURE, never as a success, so the
    # ceiling is finite and deliberately generous: 60 polls two seconds apart is
    # ~2 minutes of waiting for a job Xray itself has already accepted. Tests
    # override both, plus _sleep, so no suite ever waits in real time.
    POLL_MAX_ATTEMPTS = 60
    POLL_INTERVAL_SECONDS = 2.0

    def __init__(self, platform, base_url, credentials, transport, cloud_host=None):
        self.platform = platform
        self.base_url = base_url
        self.credentials = credentials
        self.transport = transport
        self.cloud_host = cloud_host
        self._token = None
        self._sleep = time.sleep

    def _require_known_platform(self):
        if self.platform not in ENDPOINTS:
            raise XrayError("unknown xray_platform: %r (expected cloud or server)"
                            % self.platform)

    def _substitute(self, url):
        """Resolve the contract's two substitution tokens. Every URL from
        xray_endpoints.py -- endpoint, poll URL or step URL -- goes through
        here, so none of them can be resolved two different ways."""
        url = url.replace("{base_url}", self.base_url or "")
        url = url.replace("{cloud_host}", self.cloud_host or DEFAULT_CLOUD_HOST)
        return url

    def _endpoint(self, name):
        self._require_known_platform()
        return self._substitute(ENDPOINTS[self.platform][name])

    def authenticate(self):
        if self._token:
            return self._token
        self._require_known_platform()
        style = AUTH_STYLE[self.platform]["style"]
        if style == "token_exchange":
            self._token = self._authenticate_token_exchange()
        elif style == "per_request_header":
            self._token = self._authenticate_per_request_header()
        else:
            raise XrayError("unsupported auth style for platform %r: %r"
                            % (self.platform, style))
        return self._token

    def _authenticate_token_exchange(self):
        # Cloud only (api-contract.md, "Xray Cloud" > "1. Authentication -- auth"):
        # POST client_id/client_secret, receive a bare quoted JSON string as the
        # 200 body -- json.loads() it directly, never body["token"].
        status, _, payload = self.transport.request(
            "POST", self._endpoint("auth"),
            headers={"Content-Type": "application/json"},
            body=json.dumps(self._auth_body()).encode(),
        )
        if status != 200:
            raise XrayError("Xray authentication failed with HTTP %d" % status)
        token = json.loads(payload.decode())
        return token

    def _authenticate_per_request_header(self):
        # Server/DC only (api-contract.md, "Xray Server / Data Center" >
        # "1. Authentication -- auth"): no exchange call. The PAT goes straight
        # into the Authorization header of a GET to /myself, which is used only
        # to validate the credential -- its body (a Jira user profile) is never
        # parsed for a token. A 200 means the PAT is good; the header value we
        # already built is what gets returned and reused on every later request.
        header_value = AUTH_STYLE["server"]["header_template"].format(
            token=self._credential_value()
        )
        status, _, _ = self.transport.request(
            "GET", self._endpoint("auth"),
            headers={AUTH_STYLE["server"]["header_name"]: header_value},
        )
        if status != 200:
            raise XrayError("Xray authentication failed with HTTP %d" % status)
        return header_value

    def _credential_value(self):
        for key in ("personal_access_token", "pat", "token"):
            if key in self.credentials:
                return self.credentials[key]
        raise XrayError(
            "no personal access token found in credentials "
            "(expected key 'personal_access_token')"
        )

    def _auth_body(self):
        fields = AUTH_STYLE["cloud"]["body_fields"]
        try:
            return {field: self.credentials[field] for field in fields}
        except KeyError as e:
            raise XrayError("missing required credential field: %s" % e.args[0])

    # ---- Label matching (api-contract.md, "2. JQL search") -----------------

    JQL_BATCH = 50

    def find_tests_by_label(self, project_key, labels):
        """Map each label already present in Jira (as an issue label) to its
        issue key. Labels with no match are simply absent from the result --
        callers partition create-vs-update on that absence, so a truncated
        page here must never be mistaken for "not found"."""
        found = {}
        if not labels:
            return found
        self._require_known_platform()
        headers = self._search_auth_header()
        for start in range(0, len(labels), self.JQL_BATCH):
            chunk = labels[start:start + self.JQL_BATCH]
            quoted = ", ".join('"%s"' % label for label in chunk)
            jql = 'project = %s AND labels in (%s)' % (project_key, quoted)
            for issue in self._search_all_pages(jql, headers, project_key):
                for label in issue.get("fields", {}).get("labels", []):
                    if label in chunk:
                        found[label] = issue["key"]
        return found

    def _search_auth_header(self):
        # Cloud search is a Jira endpoint secured by Jira credentials, not the
        # Xray bearer token (api-contract.md, "Xray Cloud" > "2. JQL search").
        # Whether the Xray token is also accepted is genuinely unverified
        # (contract's ## Unverified, item 2), so this does not demand Jira
        # credentials speculatively: it prefers them when configured, and
        # otherwise tries the Xray token, turning a 401/403 into a
        # self-diagnosing error rather than guessing up front.
        if self.platform == "cloud":
            email = self.credentials.get("jira_email")
            api_token = self.credentials.get("jira_api_token")
            if email and api_token:
                basic = base64.b64encode(
                    ("%s:%s" % (email, api_token)).encode()
                ).decode()
                return {"Authorization": "Basic %s" % basic}
            return {"Authorization": "Bearer %s" % self.authenticate()}
        # Server/DC: the same Jira credential used on every other request.
        return {"Authorization": self.authenticate()}

    def _post_json(self, url, headers, body):
        all_headers = {"Content-Type": "application/json"}
        all_headers.update(headers or {})
        return self.transport.request(
            "POST", url, headers=all_headers, body=json.dumps(body).encode()
        )

    def _search_all_pages(self, jql, headers, project_key):
        if self.platform == "cloud":
            return self._search_cloud_all_pages(jql, headers, project_key)
        return self._search_server_all_pages(jql, headers, project_key)

    def _search_cloud_all_pages(self, jql, headers, project_key):
        # Cloud search/jql paginates with a returned nextPageToken, not
        # startAt (api-contract.md: "Pagination is token-based
        # (nextPageToken), not startAt-based"). The response schema for the
        # token itself is not spelled out in the contract beyond naming the
        # SearchAndReconcileResults shape, so continuation is keyed off the
        # presence of a nextPageToken in the response, mirroring the
        # request-side field of the same name; its absence is the terminal
        # condition. See task-3-report.md for this inference.
        issues = []
        body = {"jql": jql, "fields": ["labels"], "maxResults": 100}
        page_token = None
        while True:
            if page_token:
                body["nextPageToken"] = page_token
            url = self._endpoint("search")
            status, _, payload = self._post_json(url, headers, body)
            self._raise_for_search_status(status, project_key)
            data = json.loads(payload.decode())
            issues.extend(data.get("issues", []))
            page_token = data.get("nextPageToken")
            if not page_token:
                break
        return issues

    def _search_server_all_pages(self, jql, headers, project_key):
        # Server/DC search is offset-based: {"startAt", "maxResults",
        # "total", "issues"} (api-contract.md, Server "2. JQL search",
        # quoting the documented request/response shape). Keep requesting
        # while fewer issues have been seen than "total" reports.
        issues = []
        start_at = 0
        max_results = 50
        while True:
            body = {
                "jql": jql,
                "startAt": start_at,
                "maxResults": max_results,
                "fields": ["labels"],
            }
            url = self._endpoint("search")
            status, _, payload = self._post_json(url, headers, body)
            self._raise_for_search_status(status, project_key)
            data = json.loads(payload.decode())
            page = data.get("issues", [])
            issues.extend(page)
            start_at += len(page)
            total = data.get("total")
            if not page or total is None or start_at >= total:
                break
        return issues

    def _raise_for_search_status(self, status, project_key):
        if status == 200:
            return
        if self.platform == "cloud" and status in (401, 403):
            # Branch the diagnosis on whether Jira credentials are already
            # configured. A confident wrong diagnosis is worse than a vague
            # one: telling a user who already has jira_email/jira_api_token
            # to "add" them sends them down a path that cannot help.
            email = self.credentials.get("jira_email")
            api_token = self.credentials.get("jira_api_token")
            if email and api_token:
                raise XrayError(
                    "Jira search returned %d with the Jira credentials from "
                    "agent-qa/.xray-credentials. Check that jira_email and "
                    "jira_api_token are correct and that the account can "
                    "browse project %s." % (status, project_key)
                )
            raise XrayError(
                "Jira search returned %d. Xray Cloud search is a Jira "
                "endpoint and may not accept the Xray token. Add jira_email "
                "and jira_api_token to agent-qa/.xray-credentials. If the "
                "problem persists after adding them, the Xray token may "
                "have expired." % status
            )
        raise XrayError("Jira search failed with HTTP %d" % status)

    # ---- The write path ----------------------------------------------------
    #
    # Cloud and Server are two different implementations behind one contract,
    # not one implementation with a flag (api-contract.md, "Flavour differences
    # at a glance"):
    #
    #   CLOUD   one ASYNCHRONOUS Xray job. POST the whole batch to
    #           /api/v2/import/test/bulk, receive a jobId, poll the status URL
    #           until it reaches a terminal state, then read result.issues and
    #           result.errors.
    #   SERVER  no Xray bulk test-import endpoint exists -- that is a verified
    #           negative, not a gap in our research. It is plain synchronous
    #           Jira: POST /rest/api/2/issue/bulk to create the Test issues,
    #           then N further calls, one per step, per test.
    #
    # Both return the SAME {created, updated, failed} dict so that no caller
    # ever branches on platform. Two implementations, one contract.
    #
    # Partial failure is the normal case here, not the exception: one test
    # rejected by a required custom field must not cost the other twenty-nine.
    # Nothing below aborts a batch on the first failure, and nothing below
    # raises for a per-test failure -- failures accumulate in "failed" with a
    # tc_id and a reason, and upload.run() turns a non-empty "failed" into a
    # non-zero exit code.

    def _xray_auth_header(self):
        """Authorization header for a write. Cloud's authenticate() returns a
        bare JWT that still needs the Bearer prefix; Server's returns the
        finished header value, because there was never a token to extract."""
        if self.platform == "cloud":
            return {"Authorization": "Bearer %s" % self.authenticate()}
        return {"Authorization": self.authenticate()}

    @staticmethod
    def _entry_tc_id(entry):
        """The TC-ID of a canonical payload entry. build_manual_payload() puts
        it in labels[0] on both the create and the update path precisely so it
        can be recovered here -- it is also the idempotency match key."""
        if not isinstance(entry, dict):
            return "(unknown)"
        labels = (entry.get("fields") or {}).get("labels") or []
        if labels:
            return labels[0]
        return entry.get("key") or "(unknown)"

    @staticmethod
    def _error_reason(err):
        """A human-actionable reason out of a vendor error element.

        Neither the contract nor the vendor documentation pins the shape of an
        element inside Cloud's `result.errors`, so this reads defensively
        rather than asserting a schema. Jira's own bulk-create error shape
        (`elementErrors.errorMessages` / `.errors`) IS documented and is
        handled explicitly. Anything unrecognised is serialised verbatim --
        an unhelpful reason is still better than a discarded one.
        """
        if not isinstance(err, dict):
            return str(err)
        for key in ("message", "error", "reason", "errorMessage"):
            value = err.get(key)
            if isinstance(value, str) and value.strip():
                return value.strip()
        element_errors = err.get("elementErrors")
        if isinstance(element_errors, dict):
            parts = list(element_errors.get("errorMessages") or [])
            field_errors = element_errors.get("errors") or {}
            if isinstance(field_errors, dict):
                parts.extend("%s: %s" % (k, v)
                             for k, v in sorted(field_errors.items()))
            if parts:
                return "; ".join(str(p) for p in parts)
        try:
            return json.dumps(err, sort_keys=True, default=str)
        except (TypeError, ValueError):
            return str(err)

    def _error_tc_id(self, err, entries):
        """Which test an error element refers to. Index fields first (Jira
        documents failedElementNumber; Xray Cloud's elementNumber is the
        analogous field), then a literal search for any TC-ID we sent, since
        vendor messages routinely echo the summary or the label. Falls back to
        a visible "(unknown)" rather than silently attaching the failure to
        the wrong test."""
        if isinstance(err, dict):
            for key in ("failedElementNumber", "elementNumber", "index"):
                n = err.get(key)
                if isinstance(n, int) and not isinstance(n, bool) \
                        and 0 <= n < len(entries):
                    return self._entry_tc_id(entries[n])
            try:
                text = json.dumps(err, sort_keys=True, default=str)
            except (TypeError, ValueError):
                text = str(err)
            for entry in entries:
                tc_id = self._entry_tc_id(entry)
                if tc_id != "(unknown)" and tc_id in text:
                    return tc_id
        return "(unknown)"

    def _fail_all(self, entries, reason):
        results = empty_results()
        for entry in entries:
            results["failed"].append(
                {"tc_id": self._entry_tc_id(entry), "reason": reason})
        return results

    # ---- Manual tests ------------------------------------------------------

    def import_manual_tests(self, payload):
        """Create or update Manual tests from the canonical payload built by
        xray_payloads.build_manual_payload(). Returns the unified
        {created, updated, failed} dict. Never raises for a single test's
        rejection -- only for a structural problem that makes the whole batch
        uninterpretable."""
        self._require_known_platform()
        if not payload:
            return empty_results()
        if self.platform == "cloud":
            return self._import_manual_tests_cloud(payload)
        return self._import_manual_tests_server(payload)

    # ---- Manual tests: Cloud (asynchronous job) ----------------------------

    def _import_manual_tests_cloud(self, payload):
        results = empty_results()
        # Documented structural limits: at most 1000 tests per request, and at
        # most ONE import job per user at a time -- a client that fanned these
        # out concurrently would get a 400 on the second. So: sequential.
        limit = LIMITS["cloud"]["max_tests_per_bulk_import"] or len(payload)
        for start in range(0, len(payload), limit):
            chunk = payload[start:start + limit]
            merge_results(results, self._import_chunk_cloud(chunk))
        return results

    def _import_chunk_cloud(self, chunk):
        headers = self._xray_auth_header()
        status, _, body = self._post_json(
            self._endpoint("import_tests"), headers, chunk)
        if status != 200:
            return self._fail_all(
                chunk, "Xray bulk test import returned HTTP %d" % status)
        try:
            job_id = json.loads(body.decode("utf-8", "replace")).get("jobId")
        except (ValueError, AttributeError):
            job_id = None
        if not job_id:
            return self._fail_all(
                chunk, "Xray bulk test import returned no jobId, so there is "
                       "no job to poll and no way to confirm what was written")
        state, data = self._poll_import_job(job_id)
        return self._cloud_job_outcome(state, data, chunk)

    def _poll_import_job(self, job_id):
        """Poll a Cloud import job to a terminal state. Returns
        (state, response_data). A job still working when the ceiling is
        reached returns ("timeout", None): a timeout is a FAILURE, never a
        success, because nothing about it tells us what landed in Jira."""
        url = self._substitute(
            IMPORT_TESTS_STATUS[self.platform]).replace("{jobId}", str(job_id))
        headers = self._xray_auth_header()
        for attempt in range(self.POLL_MAX_ATTEMPTS):
            if attempt:
                self._sleep(self.POLL_INTERVAL_SECONDS)
            status, _, body = self.transport.request("GET", url, headers=headers)
            if status != 200:
                return "http_error", {"http_status": status}
            try:
                data = json.loads(body.decode("utf-8", "replace"))
            except ValueError:
                return "bad_body", None
            raw_status = str(data.get("status", "")).lower()
            state = IMPORT_JOB_STATUSES.get(raw_status)
            if state is None:
                # An unrecognised status is not "probably fine". Stop loudly
                # rather than poll forever or guess it means success.
                raise XrayError(
                    "Xray import job reported an unrecognised status %r "
                    "(expected one of: %s). See %s."
                    % (raw_status, ", ".join(sorted(IMPORT_JOB_STATUSES)),
                       CONTRACT_DOC))
            if state.startswith("terminal"):
                return state, data
        return "timeout", None

    def _cloud_job_outcome(self, state, data, chunk):
        if state == "timeout":
            return self._fail_all(
                chunk,
                "the Xray import job was still running after %d status polls "
                "(~%d seconds) and was not confirmed. It may yet complete -- "
                "check the project in Jira before re-running, or this batch "
                "could be created twice."
                % (self.POLL_MAX_ATTEMPTS,
                   int(self.POLL_MAX_ATTEMPTS * self.POLL_INTERVAL_SECONDS)))
        if state == "http_error":
            return self._fail_all(
                chunk, "polling the Xray import job returned HTTP %d, so the "
                       "outcome of this batch is unknown" % data["http_status"])
        if state == "bad_body":
            return self._fail_all(
                chunk, "the Xray import job status response was not JSON, so "
                       "the outcome of this batch is unknown")

        result = data.get("result") or {}
        issues = result.get("issues") or []
        errors = result.get("errors") or []
        if state == "terminal_error" and not issues and not errors:
            return self._fail_all(
                chunk, "the Xray import job finished with status %r and "
                       "reported no per-test detail"
                       % str(data.get("status", "")))

        results = empty_results()
        # An entry carrying a key was sent as an update; anything else is new.
        # Matching on the key we SENT, rather than on response ordering, is
        # what keeps this correct when Xray reorders or drops entries.
        sent_update_keys = set(
            entry["key"] for entry in chunk if entry.get("key"))
        for issue in issues:
            key = issue.get("key")
            if key in sent_update_keys:
                results["updated"].append(key)
            else:
                results["created"].append(key)
        for err in errors:
            results["failed"].append({"tc_id": self._error_tc_id(err, chunk),
                                      "reason": self._error_reason(err)})

        # Reconciliation. If the job reports fewer outcomes than tests we sent,
        # some test neither succeeded nor was reported as failing -- a silent
        # disappearance. Report the shortfall rather than letting the counts
        # quietly add up to "everything worked".
        reported = len(issues) + len(errors)
        if reported < len(chunk):
            results["failed"].append({
                "tc_id": "(unreported)",
                "reason": "the Xray import job reported an outcome for only "
                          "%d of the %d tests sent in this batch; %d test(s) "
                          "cannot be confirmed as created, updated or failed"
                          % (reported, len(chunk), len(chunk) - reported),
            })
        return results

    # ---- Manual tests: Server/DC (synchronous Jira + N step calls) ---------

    def _import_manual_tests_server(self, payload):
        headers = self._xray_auth_header()
        creates = [entry for entry in payload if not entry.get("key")]
        updates = [entry for entry in payload if entry.get("key")]

        results = empty_results()
        for entry in updates:
            # Xray Server/DC has no bulk test import and the contract records
            # no update endpoint for an existing Test issue. Rather than
            # quietly re-creating it (a duplicate) or quietly doing nothing and
            # calling it "updated" (a silent success), say so, per test, and
            # let the non-zero exit carry the news.
            results["failed"].append({
                "tc_id": self._entry_tc_id(entry),
                "reason": "already exists in Jira as %s, and no update "
                          "endpoint for an existing Test issue is recorded in "
                          "%s for Xray Server/DC. It was left untouched -- "
                          "edit it in Jira, or delete it and re-run to "
                          "recreate it." % (entry["key"], CONTRACT_DOC),
            })
        if creates:
            merge_results(results, self._bulk_create_server(creates, headers))
        return results

    def _server_issue_update(self, entry):
        """One element of Jira's {"issueUpdates": [...]} bulk-create body.

        The canonical payload is shaped for Cloud's Xray import, which carries
        the Xray test type in a top-level "testtype". Jira's own bulk create
        knows nothing about that field and requires a Jira "issuetype" instead;
        Xray Server/DC's Test issues use the issue type named "Test". Sending
        the canonical "testtype" through would be rejected as an unknown field,
        so it is translated here rather than passed on.
        """
        fields = dict(entry.get("fields") or {})
        fields.setdefault("issuetype", {"name": "Test"})
        return {"fields": fields}

    def _bulk_create_server(self, creates, headers):
        body = {"issueUpdates": [self._server_issue_update(e) for e in creates]}
        status, _, raw = self._post_json(
            self._endpoint("import_tests"), headers, body)
        if status not in (200, 201):
            return self._fail_all(
                creates, "Jira bulk issue create returned HTTP %d" % status)
        try:
            data = json.loads(raw.decode("utf-8", "replace"))
        except ValueError:
            return self._fail_all(
                creates, "Jira bulk issue create returned a body that is not "
                         "JSON, so the outcome of this batch is unknown")

        issues = data.get("issues") or []
        errors = data.get("errors") or []

        results = empty_results()
        failed_indexes = set()
        for err in errors:
            index = err.get("failedElementNumber") if isinstance(err, dict) else None
            if isinstance(index, int) and not isinstance(index, bool) \
                    and 0 <= index < len(creates):
                failed_indexes.add(index)
                tc_id = self._entry_tc_id(creates[index])
            else:
                tc_id = self._error_tc_id(err, creates)
            results["failed"].append({"tc_id": tc_id,
                                      "reason": self._error_reason(err)})

        # Jira returns created issues in the order of the issueUpdates entries
        # that survived, and names the ones that did not via
        # failedElementNumber -- so the survivors line up positionally with
        # "issues". If they do not line up, the mapping is not trustworthy and
        # a mis-attributed step write would be worse than a reported shortfall.
        survivors = [entry for i, entry in enumerate(creates)
                     if i not in failed_indexes]
        if len(issues) != len(survivors):
            results["failed"].append({
                "tc_id": "(unreported)",
                "reason": "Jira bulk issue create returned %d issue(s) for %d "
                          "test(s) that it did not report as failing; the "
                          "remainder cannot be confirmed"
                          % (len(issues), len(survivors)),
            })

        for entry, issue in zip(survivors, issues):
            key = issue.get("key")
            if not key:
                results["failed"].append({
                    "tc_id": self._entry_tc_id(entry),
                    "reason": "Jira bulk issue create returned an issue with "
                              "no key, so its steps could not be written",
                })
                continue
            step_failure = self._create_server_steps(key, entry, headers)
            if step_failure:
                results["failed"].append({"tc_id": self._entry_tc_id(entry),
                                          "reason": step_failure})
            else:
                results["created"].append(key)
        return results

    def _create_server_steps(self, test_key, entry, headers):
        """Write a Server/DC Test's manual steps, one HTTP call per step.
        Returns None on success, or a reason string naming the step that
        failed. Jira's bulk create makes the Test ISSUE; it does not and
        cannot make its steps -- without this loop every test lands empty.

        ==================== RULING 10 -- PINNED API VERSION ====================
        READ THIS BEFORE CHANGING THE URL BELOW.

        Xray Server/DC exposes TWO step APIs. They are NOT interchangeable
        (api-contract.md, "Server step API -- two versions, two different body
        shapes"):

            v1.0  PUT  {base_url}/rest/raven/1.0/api/test/{testKey}/step
                  flat, lowercase body:
                      {"step": ..., "data": ..., "result": ...}

            v2.0  POST {base_url}/rest/raven/2.0/api/test/{testKey}/steps
                  Jira DISPLAY-NAME keys nested under "fields":
                      {"fields": {"Action": ..., "Data": ...,
                                  "Expected Result": ...}}

        Note also "step" (singular) on v1.0 versus "steps" (plural) on v2.0.

        We pin v1.0, via SERVER_TEST_STEP_URL in xray_endpoints.py.

        THE TRAP: if someone "upgrades" this by swapping only the URL to the
        2.0 path and leaves the flat v1.0 body below in place, Xray accepts the
        request and answers 2xx -- and creates steps with EMPTY FIELDS. No
        error. No non-2xx. Nothing in this function, nothing in the results
        dict, and nothing in the upload report would show a problem: every test
        lands in Jira looking correct and containing nothing, and the first
        person to find out is a tester who opens one weeks later.

        So: changing the URL REQUIRES changing the serialiser in the same edit.
        v1.0 also stays pinned because v2.0's display-name casing is itself
        unverified -- those are instance-specific, localisable Jira custom-field
        names, and the vendor's own collection spells the first one "action" in
        one example and "Action" in another (api-contract.md, "## Unverified"
        item 3). Guessing wrong there produces exactly the same empty steps.
        ========================================================================
        """
        url_template = self._substitute(SERVER_TEST_STEP_URL)
        url = url_template.replace("{testKey}", test_key)
        for number, step in enumerate(entry.get("steps") or [], start=1):
            # The canonical payload uses Cloud's manual-step schema
            # (action/data/result). v1.0 spells the first key "step". Same
            # values, this flavour's field names -- this translation is the
            # other half of the pinning above.
            body = {
                "step": step.get("action", ""),
                "data": step.get("data", ""),
                "result": step.get("result", ""),
            }
            status, _, _ = self.transport.request(
                "PUT", url,
                headers=dict(list(headers.items())
                             + [("Content-Type", "application/json")]),
                body=json.dumps(body).encode(),
            )
            if status not in (200, 201, 204):
                return ("created in Jira as %s, but writing step %d of %d "
                        "returned HTTP %d -- the test exists with incomplete "
                        "steps and needs fixing in Jira"
                        % (test_key, number, len(entry.get("steps") or []),
                           status))
        return None

    # ---- Gherkin feature import (synchronous on both flavours) -------------

    def import_feature_file(self, path, project_key, existing_keys=None):
        """Import one .feature file, creating or updating its Cucumber tests.
        Returns the same unified {created, updated, failed} dict as
        import_manual_tests(). `existing_keys` is the label->issue-key map from
        find_tests_by_label(); it is what separates "updated" from "created",
        since both flavours answer with a single "updated or created" list."""
        self._require_known_platform()
        name = os.path.basename(path)
        try:
            with open(path, "rb") as fh:
                content = fh.read()
        except OSError as e:
            return {"created": [], "updated": [], "failed": [
                {"tc_id": name, "reason": "could not read the feature file: %s" % e}]}

        max_bytes = LIMITS[self.platform]["max_feature_upload_bytes"]
        if max_bytes and len(content) > max_bytes:
            return {"created": [], "updated": [], "failed": [
                {"tc_id": name,
                 "reason": "the feature file is %d bytes, over the documented "
                           "%d byte upload limit" % (len(content), max_bytes)}]}

        parts = FEATURE_IMPORT_PARTS[self.platform]
        # Only the "file" part is sent. The optional precondition part is
        # spelled precondInfo on Cloud and preCondInfo on Server, and the
        # contract flags that casing as unverified -- and because the part is
        # OPTIONAL, a wrong spelling is ignored in silence rather than
        # rejected. Not sending it is the only way to not be silently wrong.
        body, content_type = _encode_multipart_file(parts["file"], name, content)

        query = urllib.parse.urlencode({"projectKey": project_key})
        url = "%s?%s" % (self._endpoint("import_feature"), query)
        headers = self._xray_auth_header()
        headers["Content-Type"] = content_type
        status, _, raw = self.transport.request(
            "POST", url, headers=headers, body=body)
        if status != 200:
            # Both flavours answer errors as text/plain, so there is no JSON
            # body to mine for a reason here.
            return {"created": [], "updated": [], "failed": [
                {"tc_id": name,
                 "reason": "feature import returned HTTP %d" % status}]}
        return self._feature_outcome(raw, name, existing_keys)

    def _feature_outcome(self, raw, name, existing_keys):
        try:
            data = json.loads(raw.decode("utf-8", "replace"))
        except ValueError:
            return {"created": [], "updated": [], "failed": [
                {"tc_id": name,
                 "reason": "feature import answered 200 with a body that is "
                           "not JSON, so nothing about it can be confirmed"}]}

        # Cloud answers an object with three lists; Server answers a bare JSON
        # array of issues, and labels it application/octet-stream, so the
        # Content-Type header is not worth consulting -- branch on the parsed
        # shape instead (api-contract.md, both "4. ... feature import").
        if isinstance(data, list):
            touched, errors = data, []
        elif isinstance(data, dict):
            touched = data.get("updatedOrCreatedTests") or []
            errors = data.get("errors") or []
        else:
            return {"created": [], "updated": [], "failed": [
                {"tc_id": name,
                 "reason": "feature import answered 200 with an unexpected "
                           "body shape (%s)" % type(data).__name__}]}

        already = set((existing_keys or {}).values())
        results = empty_results()
        for issue in touched:
            key = issue.get("key") if isinstance(issue, dict) else None
            if not key:
                continue
            if key in already:
                results["updated"].append(key)
            else:
                results["created"].append(key)
        for err in errors:
            results["failed"].append({"tc_id": name,
                                      "reason": self._error_reason(err)})
        return results
